In [2]:
import numpy as np

names = np.array(["raj", "sam" , "shine"])


In [3]:
for name in names:
    print(name)
#faster than regular list in python

raj
sam
shine


In [4]:
a = [[3,35,32] , [6,4,4]]
arr = np.array(a)


In [6]:
arr

array([[ 3, 35, 32],
       [ 6,  4,  4]])

In [7]:
arr.shape

(2, 3)

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.full([3,2] , 5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])