In [ ]:
import numpy as np
from numpy.ma.core import size

names = np.array(["raj", "sam" , "shine"])


In [ ]:
for name in names:
    print(name)
#faster than regular list in python

In [ ]:
a = [[3,35,32] , [6,4,4]]
arr = np.array(a)


In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
np.zeros(3)

In [17]:
arra = np.random.seed(43)

In [ ]:
np.full([3,2] , 5)

In [ ]:
np.eye(4)

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
array = np.random.randint(0 , 10 , size=(3,6))
array

array([[4, 4, 0, 5, 8, 0],
       [0, 9, 2, 0, 4, 4],
       [8, 9, 7, 4, 8, 5]], dtype=int32)

In [21]:
array.shape

(3, 6)

In [22]:
array.size

18

In [23]:
array.ndim

2

In [24]:
array.dtype

dtype('int32')

In [25]:
array.itemsize

4

In [26]:
array.nbytes

72

In [27]:
array.T


array([[4, 0, 8],
       [4, 9, 9],
       [0, 2, 7],
       [5, 0, 4],
       [8, 4, 8],
       [0, 4, 5]], dtype=int32)

In [32]:
num = np.random.randint(0 , 10 , size=(6,4))
num

array([[7, 4, 5, 3],
       [5, 3, 8, 3],
       [5, 1, 6, 0],
       [0, 7, 1, 3],
       [1, 5, 8, 0],
       [3, 6, 9, 4]], dtype=int32)

In [33]:
num[0:3]

array([[7, 4, 5, 3],
       [5, 3, 8, 3],
       [5, 1, 6, 0]], dtype=int32)

In [34]:
num[1:4 , 2:]

array([[8, 3],
       [6, 0],
       [1, 3]], dtype=int32)

In [35]:
num[2]

array([5, 1, 6, 0], dtype=int32)